import yaml
import json
from fastapi import FastAPI, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Dict, Any
from starlette.middleware.base import BaseHTTPMiddleware
import redis

# Load Config
with open("../config.yaml", "r") as f:
    config = yaml.safe_load(f)

app = FastAPI(title="MaintenanceAI Copilot Backend")

# Ultimate CORS bypass middleware
class CorsBypassMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        if request.method == "OPTIONS":
            response = Response()
        else:
            response = await call_next(request)
        
        response.headers["Access-Control-Allow-Origin"] = "*"
        response.headers["Access-Control-Allow-Methods"] = "*"
        response.headers["Access-Control-Allow-Headers"] = "*"
        return response

app.add_middleware(CorsBypassMiddleware)

redis_url = config['queue'].get('redis_url', 'redis://127.0.0.1/')
r_client = redis.Redis.from_url(redis_url, decode_responses=True)

class ChatRequest(BaseModel):
    message: str
    incident_context: Dict[str, Any]
    history: List[Dict[str, str]] = []

@app.get("/api/incidents")
async def get_incidents():
    """
    Fetch the latest anomalies generated by the Python Worker from a Redis list.
    (We'll update worker.py to push generated insights to 'active_incidents')
    """
    try:
        raw_incidents = r_client.lrange("active_incidents", 0, 50)
        incidents = []
        for raw in raw_incidents:
            incidents.append(json.loads(raw))
        return {"incidents": incidents}
    except Exception as e:
        print(f"Error fetching incidents: {e}")
        return {"incidents": []}

@app.get("/api/logs")
async def get_logs():
    """
    Fetch the raw log stream for the dashboard.
    We pull the last 100 messages from the main maintenance_logs stream.
    """
    try:
        # XREVRANGE to get newest logs first
        messages = r_client.xrevrange("maintenance_logs", "+", "-", count=100)
        logs = []
        for msg_id, msg_data in messages:
            raw_json = msg_data.get("log_data")
            if raw_json:
                logs.append(json.loads(raw_json))
        return {"logs": logs}
    except Exception as e:
        print(f"Error fetching logs: {e}")
        return {"logs": []}


@app.post("/api/chat")
async def chat_endpoint(req: ChatRequest):
    try:
        system_prompt = f"""
You are an AI Copilot assisting a Site Reliability Engineer (SRE).
They are currently investigating this incident:
{json.dumps(req.incident_context, indent=2)}

You can answer their questions using text. 
IF you need to show them a graph, a chart, or visual data, you MUST use the AG-UI protocol.
To render a chart, output a markdown block exactly like this:
```ag-ui
{{
  "type": "BarChart",
  "title": "Error Rates",
  "labels": ["10:00", "10:05", "10:10"],
  "datasets": [
    {{ "label": "500 Errors", "data": [5, 12, 45] }}
  ]
}}
```
Supported types: BarChart, LineChart.
Be concise.
"""
        import requests
        import os
        
        url = config['llm'].get('base_url', 'https://ollama.com/api/chat')
        headers = {'Content-Type': 'application/json'}
        api_key = config.get("keys", {}).get("ollama", "")
        if api_key: headers['Authorization'] = f'Bearer {api_key}'
        
        messages = [{"role": "system", "content": system_prompt}]
        for h in req.history:
            messages.append(h)
        messages.append({"role": "user", "content": req.message})
        
        payload = {
            "model": config['llm'].get('model', 'gpt-oss:120b'),
            "messages": messages,
            "stream": False
        }
        
        print(f"Sending prompt to Ollama Cloud...", flush=True)
        resp = requests.post(url, headers=headers, json=payload, timeout=60)
        resp.raise_for_status()
        data = resp.json()
        return {"reply": data.get("message", {}).get("content", "")}

    except Exception as e:
        print(f"Chat Error: {e}", flush=True)
        raise HTTPException(status_code=500, detail=str(e))



import httpx
import base64

@app.post("/api/vision")
async def vision_endpoint(req: Request):
    try:
        data = await req.json()
        image_url = data.get("imageUrl")
        if not image_url:
            raise HTTPException(status_code=400, detail="Missing imageUrl")
            
        async with httpx.AsyncClient() as client:
            img_resp = await client.get(image_url)
            img_resp.raise_for_status()
            b64 = base64.b64encode(img_resp.content).decode("utf-8")
            
        prompt = "Analyze this CCTV traffic/surveillance image. Output exactly valid JSON with no markdown formatting. The JSON must contain a 'description' string giving a 1-sentence general summary, and an 'incidents' array of short strings indicating any detected anomalies (e.g., 'Heavy congestion', 'Vehicle accident', 'Pedestrian on road', etc). If normal, the incidents array should be empty."
        
        api_key = config.get("keys", {}).get("ollama", "")
        
        payload = {
            "model": "qwen3-vl:235b-instruct",
            "messages": [{"role": "user", "content": prompt, "images": [b64]}],
            "stream": False,
            "format": "json",
            "options": {"temperature": 0.1}
        }
        
        headers = {"Content-Type": "application/json"}
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"
            
        async with httpx.AsyncClient() as client:
            resp = await client.post("https://ollama.com/api/chat", headers=headers, json=payload, timeout=60.0)
            resp.raise_for_status()
            res_data = resp.json()
            content = res_data.get("message", {}).get("content", "{}").strip()
            
            if content.startswith("```"):
                lines = content.split("\n")
                if lines[0].startswith("```"): lines.pop(0)
                if lines[-1].startswith("```"): lines.pop()
                content = "\n".join(lines).strip()
                
            return Response(content=content, media_type="application/json")
    except Exception as e:
        print(f"Vision Error: {e}", flush=True)
        raise HTTPException(status_code=500, detail=str(e))
